### ISSUE TITLE
some problems in the analysis of multi-component hydrogen bonds

### ISSUE THREAD

**Issue by AHeLaterr** [ccdc-opensource/csd-python-api-scripts#47]
Hello, I encountered some problems in the analysis of multi-component hydrogen bonds, which was done in full accordance with the official tutorial, but the calculation of each coformer failed, and the final output list was empty without output report. The specific error is as follows:

acetophenone_oxime
(FunctionalGroup(hydroxyimino_2), FunctionalGroup(ar_al_ether_1), FunctionalGroup(sulfinyl_1), FunctionalGroup(imidazole_1), FunctionalGroup(ar_N_2))
1689 structures
hydroxyimino_2:   501 (good number)
 ar_al_ether_1:   501 (good number)
    sulfinyl_1:   246 (maybe sufficient)
   imidazole_1:   501 (good number)
        ar_N_2:   501 (good number)
OH1(atom 0 of hydroxyimino_2) 830 859
NH1(atom 3 of imidazole_1) 642 584
N(atom 1 of hydroxyimino_2) 414 377
OH1(atom 0 of hydroxyimino_2) 177 542
O(atom 0 of ar_al_ether_1) 95 439
O(atom 0 of sulfinyl_1) 225 32
N(atom 0 of imidazole_1) 447 369
N(atom 1 of ar_N_2) 378 262
Propensity calculation failure for acetophenone_oxime!

Traceback (most recent call last):
  File "multi_component_hydrogen_bond_propensity_report.py", line 406, in <module>
    main(args.input_structure, args.directory, args.coformer_library, refcode)
  File "multi_component_hydrogen_bond_propensity_report.py", line 360, in main
    chart_file = make_mc_chart(mc_hbp_screen, directory, api_molecule)
  File "multi_component_hydrogen_bond_propensity_report.py", line 92, in make_mc_chart
    ymin = min(results)
ValueError: min() arg is an empty sequence

┭┮﹏┭┮ please help me

**Comment by pmbulit** [comment]
[sad]   Pablo Martinez-Bulit reacted to your message:
________________________________

**Comment by pmbulit** [comment]
Hi @AHeLaterr,
Could you send the mol2 file of the API you are using to run MCHBP to support@ccdc.cam.ac.uk so we can have a look at it?
Thanks!

**Comment by Luke2Sky** [comment]
Hi, I think we can try and solve this problem. I already reported to the CCDC team that the R installation in the new version is broken. I will probably try and modify the multi component hydrogen bond propensity to avoid a generic try-catch statement that difficult the solving of errors. What did I do to solve this problem: I downloaded R from my distro repository and copied the binaries to the API conda environment. ~/anaconda3/envs/ccdc/lib/python3.9/site-packages/ccdc/resources/rstatistics. Just delete everything and replace with your R directory. Obs.: Remember to fix broken symlinks and just use binaries instead of symlinks to binaries.

**Comment by Luke2Sky** [comment]
One suggestion that would help everyone very much was if the API got an GitHub for issues. I am not asking for it to be open sourced, just to have an issue page in GitHub like the Obsidian team has.

**Comment by pmbulit** [comment]
Hi @Luke2Sky. I think the issue you are describing with R was fixed for 2023.2, are you on the latest version?
And thank you for the suggestion, will pass it along and we'll see if it is feasible to implement

**Comment by Luke2Sky** [comment]
@pmbulit I realized I made a mistake. The problem is in the API. I used the condo channel to install the API in a new computer after 2023.2. Unless the API itself was updated the problem is still there in Linux. I will verify later if there is a new version of the API in the conda channel.

**Comment by pmbulit** [comment]
Hi @Luke2Sky. Thanks for the additional information. We've followed up on your support case by email. I am going to close the issue now but please keep using these for script-specific problems you encounter.
